### ISSUE TITLE
Fix unicode encode error that popped up recently

### ISSUE THREAD

**Issue by amoeba** [ec-geolink/d1lod#37]
I thought I caught these but it appears there's one more:

`d1lod.jobs.add_dataset(<d1lod.sesame.repository.Repository instance at 0x7f7689309fc8>, <d1lod.sesame.interface.Interface instance at 0x7f768931b3f8>, 'cmhsieh.6.1', <Element 'doc' at 0x7f7688bafa10>) from default`

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/d1lod/d1lod/jobs.py", line 348, in add_dataset
    interface.addDataset(identifier, doc)
  File "/d1lod/d1lod/sesame/interface.py", line 444, in addDataset
    self.addPerson(person)
  File "/d1lod/d1lod/sesame/interface.py", line 743, in addPerson
    person_uri = self.findPersonURI(record)
  File "/d1lod/d1lod/sesame/interface.py", line 858, in findPersonURI
    find_result = self.repository.query(query_string)
  File "/d1lod/d1lod/sesame/repository.py", line 433, in query
    print query_string
UnicodeEncodeError: 'ascii' codec can't encode character u'\u8b1d' in position 127: ordinal not in range(128)
```

**Comment by amoeba** [comment]
List of some pids that fail:
- sschen.7.2
- sschen.7.1
- sschen.7.4
- cmhsieh.6.1
- cmhsieh.6.4
