### ISSUE TITLE
Update docker-compose.yml for 2019

### ISSUE THREAD

**Issue by amoeba** [ec-geolink/d1lod#56]
- upgrade to version 3 and 'services'
- consider volumes instead of host bindings. Probably stick with host bindings
- https://docs.docker.com/compose/production/

**Comment by rushirajnenuji** [comment]
Hi @amoeba  - 

Here's a quick update on this issue:

Completed the docker-compose.yml to v3.0. All the issues w.r.t. volumes have been solved. Facing a small networking issue: In the updated `docker-compose` v 3.0 I'm repeatedly seeing  this error:
`ConnectionError: ('Connection aborted.', error(99, 'Cannot assign requested address'))`

It seems like the v3.0 creates a shared network (default) since we do not explicitly create a top level named network. When d1lod tries to make a HTTP request we encounter the above error. This might be related to having different `hostnames` in the codebase. For instance -
`redis`: hostname is set to `localhost`,
`virtuoso`: hostname is set to `virtuoso`, and so on...

My first guess would be to try using the service names (defined in the `docker-compose`) as hostnames in the configuration. Still trying to explore other solutions..
[Docker Networking Documentation](https://docs.docker.com/compose/networking/)

**Comment by amoeba** [comment]
Thanks for the update. That sounds good!

**Comment by amoeba** [comment]
@rushirajnenuji and I just chatted about this now and I took a look at the error from my end. I _think_ the problem here is that Virtuoso is crashing.

```
virtuoso_1   | 22:20:25 Roll forward started
virtuoso_1   | 22:20:25 The transaction log file has been produced by server version '07.20.3215'. The version of this server is '07.20.3229'. If the transaction log is empty or you do not want to replay it then delete it and start the server again. Otherwise replay the log using the server of version '07.20.3215' and make checkpoint and shutdown to ensure that the log is empty, then delete it and start using new version.
virtuoso_1   | 22:20:25 Server exiting
```

I also get a slightly different error:

````
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python2.7/site-packages/rq/worker.py", line 568, in perform_job
worker_1     |     rv = job.perform()
worker_1     |   File "/usr/local/lib/python2.7/site-packages/rq/job.py", line 495, in perform
worker_1     |     self._result = self.func(*self.args, **self.kwargs)
worker_1     |   File "/d1lod/d1lod/jobs.py", line 217, in calculate_stats
worker_1     |     Interface(g)  # Adds namespaces we need to repo
worker_1     |   File "/d1lod/d1lod/interface.py", line 84, in __init__
worker_1     |     self.graph.insert(RDF.Uri(prov+'wasRevisionOf'), RDF.Uri(owl+'inverseOf'), RDF.Uri(prov+'hadRevision'))
worker_1     |   File "/d1lod/d1lod/graph.py", line 225, in insert
worker_1     |     return (self.insert_data(payload=payload_string, blank_node=blank_node))
worker_1     |   File "/d1lod/d1lod/graph.py", line 248, in insert_data
worker_1     |     return (self.query(query_string=insert_query, blank_node=blank_node))
worker_1     |   File "/d1lod/d1lod/graph.py", line 349, in query
worker_1     |     r = self.session.post(endpoint, params=params, auth=('dba', 'dev.nceas'))
worker_1     |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in post
worker_1     |     return self.request('POST', url, data=data, json=json, **kwargs)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
worker_1     |     resp = self.send(prep, **send_kwargs)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
worker_1     |     r = adapter.send(request, **kwargs)
worker_1     |   File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
worker_1     |     raise ConnectionError(err, request=request)
worker_1     | ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

The above is a hostname issue and not a connection issue so the previous hypothesis about networking and hostnames seems likely to still be involved. I'm going to work on getting Virtuoso back in order first.

**Comment by amoeba** [comment]
Specifying volumes with default parameters makes Virtuoso happy again. i.e.,

```
volumes:
  www-home:
  d1lod-home: {}
  virtuoso-home: {}
  redis-home: {}
  webapps-home: {}
```

@rushirajnenuji was there a reason to specify the custom details?

```
    driver: local
    driver_opts:
      type: none
      device: $PWD/www/
      o: bind
```

(This breaks the installation of the d1lod package in the scheduler and worker containers but that's fine since we also have an issue to properly install the package rather than just adding it to `PYTHON_PATH` which was a short-term hack).

**Comment by rushirajnenuji** [comment]
Hey @amoeba -

I had default parameters for the top level defined volumes but docker was complaining about passing on empty volumes (without creating one). Or maybe I thought that is what it was complaining about. So I created the custom defined volumes from within the `docker-compose`. I might be doing something wrong.

So, yeah that and the breaking of `PYTHON-PATH` specific installation in the scheduler and worker containers are the only reason that I went for a custom defined volume. But given [this ticket #53](https://github.com/ec-geolink/d1lod/issues/53) - are there any other improvements we need to make to our current `docker-compose` or are we good to mark this as done?

**Comment by amoeba** [comment]
> I had default parameters for the top level defined volumes but docker was complaining about passing on empty volumes (without creating one). Or maybe I thought that is what it was complaining about. So I created the custom defined volumes from within the docker-compose. I might be doing something wrong.

I'm not really sure but, best I could tell, the defaults should be fine.

Here's my patch, which gets the service back to where it runs, except ELK isn't all hooked in right now with the container images updated. Could you look over what I did and see if it all makes sense?

<details>
<summary>d1lod.patch</summary>

```patch
diff --git a/d1lod/d1lod/jobs.py b/d1lod/d1lod/jobs.py
index 9bb4da7..7e7d398 100644
--- a/d1lod/d1lod/jobs.py
+++ b/d1lod/d1lod/jobs.py
@@ -36,12 +36,7 @@ NAMESPACES = {
     'd1node': 'https://cn.dataone.org/cn/v1/node/'
 }
 
-if os.environ.get('REDIS_NAME') is not None:
-    redis_host = 'redis'
-else:
-    redis_host = 'localhost'
-
-conn = StrictRedis(host=redis_host, port='6379')
+conn = StrictRedis(host='redis', port='6379')
 queues = {
     'default': Queue('default', connection=conn),
     'dataset': Queue('dataset', connection=conn),
diff --git a/docker-compose.yml b/docker-compose.yml
index 550e768..1d9c164 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -24,27 +24,18 @@ services:
 
   worker:
     build: worker
-    links:
-      - web
-      - redis
-      - virtuoso
-    volumes:
-      - d1lod-home:/d1lod
-      - www-home:/www
     environment:
       - PYTHONPATH=/d1lod:/usr/lib/python2.7/dist-packages
+    volumes:
+      - ./d1lod:/d1lod
     restart: always
 
   scheduler:
     build: scheduler
-    links:
-      - web
-      - redis
-      - virtuoso
-    volumes:
-      - d1lod-home:/d1lod
     environment:
       - PYTHONPATH=/d1lod:/usr/lib/python2.7/dist-packages
+    volumes:
+      - ./d1lod:/d1lod
     restart: always
 
   redis:
@@ -52,8 +43,6 @@ services:
     volumes:
       - redis-home:/data
     restart: always
-    ports:
-      - "6379:6379"
 
   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
@@ -117,33 +106,7 @@ services:
       - "9181:9181"
 
 volumes:
-  www-home:
-    driver: local
-    driver_opts:
-      type: none
-      device: $PWD/www/
-      o: bind
-  d1lod-home:
-    driver: local
-    driver_opts:
-      type: none
-      device: $PWD/d1lod/
-      o: bind
-  virtuoso-home:
-    driver: local
-    driver_opts:
-      type: none
-      device: $PWD/data/virtuoso/
-      o: bind
-  redis-home:
-    driver: local
-    driver_opts:
-      type: none
-      device: $PWD/data/redis/
-      o: bind
-  webapps-home:
-    driver: local
-    driver_opts:
-      type: none
-      device: $PWD/webapps/
-      o: bind
+  www-home: {}
+  virtuoso-home: {}
+  redis-home: {}
+  webapps-home: {}
diff --git a/scheduler/schedule.py b/scheduler/schedule.py
index 1248498..ec4eea8 100644
--- a/scheduler/schedule.py
+++ b/scheduler/schedule.py
@@ -6,6 +6,8 @@ from redis import StrictRedis
 from rq import Queue
 from apscheduler.schedulers.blocking import BlockingScheduler
 
+import sys
+sys.path.append('/d1lod')
 from d1lod import jobs
 
 conn = StrictRedis(host='redis', port='6379')
@@ -28,9 +30,9 @@ def queue_stats_job():
     queues['default'].enqueue(jobs.calculate_stats)
 
 
-@sched.scheduled_job('interval', id='export', hours=1)
-def queue_export_job():
-    queues['export'].enqueue(jobs.export_graph)
+# @sched.scheduled_job('interval', id='export', hours=1)
+# def queue_export_job():
+#     queues['export'].enqueue(jobs.export_graph)
 
 # Wait a bit for Sesame to start
 time.sleep(10)
@@ -38,6 +40,7 @@ time.sleep(10)
 # Queue the stats job first. This creates the graph before any other
 # jobs are run.
 queues['default'].enqueue(jobs.calculate_stats)
+queues['default'].enqueue(jobs.update_graph)
 
 # Start the scheduler
 sched.start()

```

</details>

**Comment by rushirajnenuji** [comment]
Hey @amoeba  - thanks for the suggested `patch`. The above commit includes the same patch and system works great as expected. Ready for review.

**Comment by amoeba** [comment]
LGTM, thanks @rushirajnenuji! Thanks for doing the conversion.
